platform :ios, '9.0'

target 'TableViewNew' do

  pod 'YYModel'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'MLeaksFinder','>=1.0.0'
  pod 'FBRetainCycleDetector'
  ### 后续开启CCache功能时开启
  post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        #关闭 Enable Modules
        config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        # 在生成的 Pods 项目文件中加入 CC 参数，路径的值根据你自己的项目来修改
        config.build_settings['CC'] = '$(PODS_ROOT)/ccache-clang'
      end
    end
    # 拷贝主工程的ccache-clang文件到Pods下面
    FileUtils.cp('ccache-clang', 'Pods/ccache-clang')
  end

end
